fieldLayouts:
  26761f5e-d11f-4e2a-b420-31f32e52c729:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0519683e-9547-4b14-99b1-6ea47b9babd4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53bb45b3-7753-4cac-ae42-891101d9abe6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 94afab95-a943-4237-bda4-0741d26fe998 # Single Photo
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
