fieldLayouts:
  8d9c12f3-5398-4671-83f0-e4c1f3d28d7e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 55547a55-e832-43bb-9e2d-5cdd82cd23d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8826908-e1a9-4a6f-952d-348bca231066 # Photo Gallery Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ffa3bc6-4a41-4375-9db1-1be80800fbb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 595f16f9-a6af-4994-ac29-306de64f4b48 # Album Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45d773cc-38d9-4234-9689-1b9c71f60f55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ade2a4e-3fba-4988-85bb-7e8ca1339e2b
        userCondition: null
handle: gallery
hasTitleField: true
name: Gallery
section: 79f280a5-aa33-4e68-89ff-509d988d1e36 # Gallery
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
