fieldLayouts:
  04a122ef-ba4d-4654-b20c-c1d56fc3edd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Enter the title for the homepage'
            label: 'Homepage Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1cc654f2-1d87-4779-9559-b7e64f89e7cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c192db63-0d5d-4fc7-8521-00c15bd030ce # Homepage Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a7572f5-1e9d-4e46-a6c6-d4dfaa0c6be8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 103585ea-a0e7-410a-b861-9dd8b221a7a8
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: f0436691-ed67-400b-b3b6-21d2c9c01749 # Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
