columnSuffix: null
contentColumnType: string
fieldGroup: 622e36a2-f810-44e9-88ed-8e346bb20ffc # Africa
handle: africaPhotos
instructions: 'Please upload all the Africa album images here'
name: 'Africa Photos'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Image here'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:11f318ce-278d-48cd-9f41-27b7f0755b57' # Africa Gallery
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
