columnSuffix: null
contentColumnType: string
fieldGroup: 00f9fa93-5586-4fb5-8f58-8703803ad219 # Homepage
handle: homepageImage
instructions: 'Add a homepage image'
name: 'Homepage Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a homepage image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
    - 'volume:f90c6535-7583-4182-b8d8-f6bd725fb5f2'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
