columnSuffix: null
contentColumnType: string
fieldGroup: 12f7e30d-d8bd-43f6-a974-a517352d8760 # Gallery
handle: photoGalleryImages
instructions: 'Upload photo gallery images here.'
name: 'Photo Gallery Images'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ceb1335f-bd05-4e74-8065-0e87dec7bd75' # Homepage Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a photo gallery image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:06e022df-e4f7-40ca-951b-f89306eb16e3' # Photo Gallery
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
