defaultPlacement: end
enableVersioning: true
handle: africaAlbum
name: 'Africa Album'
propagationMethod: all
siteSettings:
  33cfd352-7635-4204-b3f0-a539901817cd: # craftlit
    enabledByDefault: true
    hasUrls: true
    template: africa/_entry
    uriFormat: 'africa-album/{slug}'
type: channel
