defaultPlacement: end
enableVersioning: true
handle: gallery
name: Gallery
propagationMethod: all
siteSettings:
  33cfd352-7635-4204-b3f0-a539901817cd: # craftlit
    enabledByDefault: true
    hasUrls: true
    template: gallery/_entry
    uriFormat: 'gallery/{slug}'
structure:
  maxLevels: null
  uid: 8a3994c9-a45f-4443-9c1d-cf4eb976d427
type: structure
