defaultPlacement: end
enableVersioning: true
handle: singlePhoto
name: 'Single Photo'
propagationMethod: all
siteSettings:
  33cfd352-7635-4204-b3f0-a539901817cd: # craftlit
    enabledByDefault: true
    hasUrls: true
    template: single-photo/_entry
    uriFormat: 'single-photo/{slug}'
type: channel
